package com.fiap.postech.fase4.model;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.ArrayList;
import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "UserModel")
public class UserModel {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userLogin;

    @DynamoDBAttribute
    private String userKey;

    @DynamoDBAttribute
    private String role;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private ArrayList<UUID> videosFavoritos;

}