package com.fiap.postech.fase4.model;

//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fiap.postech.fase4.model.converter.LocalDateConverter;
import lombok.AllArgsConstructor;
import lombok.Data;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Data
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "VideoModel")
public class VideoModel {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID videoId;

    @DynamoDBAttribute
    private String videoURL;

    @DynamoDBAttribute
    @NotNull(message="Campo descrição é obrigatório!")
    private String descricaoVideo;

    @DynamoDBAttribute
    private String tituloTratado;

    @DynamoDBAttribute
    @DynamoDBTypeConverted( converter = LocalDateConverter.class )
    private LocalDate dataPublicacao;

    @DynamoDBAttribute
    @NotNull(message="Campo título é obrigatório!")
    private String titulo;

    @DynamoDBAttribute
    @NotNull(message="Ao menos uma categoria deve ser selecionada!")
    private List<String> categorias;

    @DynamoDBAttribute
    private List<String> categoriasTratado;

    @DynamoDBAttribute
    private int visualizacoesUsuarios;

    public VideoModel() {

    }
}
